[phases.setup]
cmds = [
    "cd frontend && npm install",
    "cd .. && pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"

[build.args]
NODE_VERSION = "18"
PYTHON_VERSION = "3.10"

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[build.nixpkgs]
nodejs = "18"
python = "310"
