[phases.setup]
cmds = [
    # Instalar dependencias de Python
    "pip install --upgrade pip",
    "pip install uvicorn gunicorn",
    "pip install -r backend/requirements.txt",
    # Instalar dependencias de Node.js
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    # Construir el frontend
    "cd frontend && npm run build"
]

[start]
cmd = "gunicorn backend.app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"

[build.args]
NODE_VERSION = "18"
PYTHON_VERSION = "3.10"

[build.environment]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PYTHONUNBUFFERED = "true"

[build.nixpkgs]
nodejs = "18"
python = "310"
