version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: tourpackages
      POSTGRES_PASSWORD: tourpackages123
      POSTGRES_DB: tourpackages_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 