[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x']

[phases.install]
cmds = [
    'pip install -r requirements-combined.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT' 