[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300

[deploy.restartPolicy]
type = "ON_FAILURE"
maxRetries = 10
