[build]
builder = "nixpacks"
buildCommand = "cd backend && python3 -m pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --reload"
healthcheckPath = "/health"
healthcheckTimeout = 300

[deploy.env]
NODE_ENV = "production"
PYTHONPATH = "/app/backend"
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/postgres"
SECRET_KEY = "a22f7fb8e71eb643a316a4a789595ab8830d7effd276d4491dfe7bf61dfbb852"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30" 