[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/v1/"
healthcheckTimeout = 100

[deploy.restartPolicy]
type = "ON_FAILURE"
maxRetries = 10
