[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate && sleep 5 && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload"

[deploy.restartPolicy]
type = "ON_FAILURE"
maxRetries = 10
