[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "./backend/start.sh"
healthcheckTimeout = 300

[deploy.env]
NODE_ENV = "production"
PYTHONPATH = "/app"
DATABASE_URL = "postgresql://postgres:PXHesyIGOGIAHfNulLwnsNhFHndjWVIB@postgres.railway.internal:5432/railway"
SECRET_KEY = "a22f7fb8e71eb643a316a4a789595ab8830d7effd276d4491dfe7bf61dfbb852"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30" 