services:
  # Backend API
  - type: web
    name: onetp-backend-villada
    env: python
    buildCommand: bash -c "cd backend && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
    startCommand: bash -c "cd backend && source venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # Frontend
  - type: web
    name: onetp-frontend-villada
    env: node
    buildCommand: bash -c "cd frontend && npm install && npm run build"
    startCommand: bash -c "cd frontend && npm start"
    envVars:
      - key: REACT_APP_API_URL
        value: https://onetp-backend-villada.onrender.com 