# Generated by Django 5.2.3 on 2025-06-19 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPaquete',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='ícono')),
            ],
            options={
                'verbose_name': 'categoría de paquete',
                'verbose_name_plural': 'categorías de paquetes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20, verbose_name='tipo de usuario')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='es superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('duracion_dias', models.PositiveIntegerField(default=1, verbose_name='duración en días')),
                ('dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='dificultad')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='paquetes/', verbose_name='imagen principal')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('cupo_maximo', models.PositiveIntegerField(default=20, verbose_name='cupo máximo')),
                ('incluye', models.TextField(blank=True, null=True, verbose_name='qué incluye')),
                ('no_incluye', models.TextField(blank=True, null=True, verbose_name='qué no incluye')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='requisitos')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='api.categoriapaquete', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta')),
                ('fecha_viaje', models.DateField(blank=True, null=True, verbose_name='fecha de viaje')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('mercado_pago', 'Mercado Pago')], default='efectivo', max_length=20, verbose_name='método de pago')),
                ('pago_confirmado', models.BooleanField(default=False, verbose_name='pago confirmado')),
                ('fecha_confirmacion_pago', models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmación de pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('fecha_viaje', models.DateField(blank=True, null=True, verbose_name='fecha de viaje')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venta_detalles', to='api.paquete', verbose_name='paquete')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.venta', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('fecha_viaje', models.DateField(blank=True, null=True, verbose_name='fecha de viaje')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.carrito', verbose_name='carrito')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='api.paquete', verbose_name='paquete')),
            ],
            options={
                'verbose_name': 'ítem del carrito',
                'verbose_name_plural': 'ítems del carrito',
                'ordering': ['-created_at'],
                'unique_together': {('carrito', 'paquete', 'fecha_viaje')},
            },
        ),
    ]
