# Generated by Django 5.2.3 on 2025-06-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_default_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='código'),
        ),
    ]
